// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/excel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExcelParseService_ParseExcel_FullMethodName = "/excel.ExcelParseService/ParseExcel"
)

// ExcelParseServiceClient is the client API for ExcelParseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Excel解析服务
type ExcelParseServiceClient interface {
	// 解析上传的Excel文件
	ParseExcel(ctx context.Context, in *ParseExcelRequest, opts ...grpc.CallOption) (*ParseExcelResponse, error)
}

type excelParseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExcelParseServiceClient(cc grpc.ClientConnInterface) ExcelParseServiceClient {
	return &excelParseServiceClient{cc}
}

func (c *excelParseServiceClient) ParseExcel(ctx context.Context, in *ParseExcelRequest, opts ...grpc.CallOption) (*ParseExcelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseExcelResponse)
	err := c.cc.Invoke(ctx, ExcelParseService_ParseExcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExcelParseServiceServer is the server API for ExcelParseService service.
// All implementations must embed UnimplementedExcelParseServiceServer
// for forward compatibility.
//
// Excel解析服务
type ExcelParseServiceServer interface {
	// 解析上传的Excel文件
	ParseExcel(context.Context, *ParseExcelRequest) (*ParseExcelResponse, error)
	mustEmbedUnimplementedExcelParseServiceServer()
}

// UnimplementedExcelParseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExcelParseServiceServer struct{}

func (UnimplementedExcelParseServiceServer) ParseExcel(context.Context, *ParseExcelRequest) (*ParseExcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseExcel not implemented")
}
func (UnimplementedExcelParseServiceServer) mustEmbedUnimplementedExcelParseServiceServer() {}
func (UnimplementedExcelParseServiceServer) testEmbeddedByValue()                           {}

// UnsafeExcelParseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExcelParseServiceServer will
// result in compilation errors.
type UnsafeExcelParseServiceServer interface {
	mustEmbedUnimplementedExcelParseServiceServer()
}

func RegisterExcelParseServiceServer(s grpc.ServiceRegistrar, srv ExcelParseServiceServer) {
	// If the following call pancis, it indicates UnimplementedExcelParseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExcelParseService_ServiceDesc, srv)
}

func _ExcelParseService_ParseExcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseExcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExcelParseServiceServer).ParseExcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExcelParseService_ParseExcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExcelParseServiceServer).ParseExcel(ctx, req.(*ParseExcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExcelParseService_ServiceDesc is the grpc.ServiceDesc for ExcelParseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExcelParseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "excel.ExcelParseService",
	HandlerType: (*ExcelParseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseExcel",
			Handler:    _ExcelParseService_ParseExcel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/excel.proto",
}
